name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      matrix:
        node_version: ['20.x']
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm
          registry-url: "https://npm.pkg.github.com"

      - name: Install
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
